# frozen_string_literal: true

source "https://rubygems.org"

ruby "3.2.8"

# Framework principal
gem "rails", "~> 7.1.6"

# Base de datos
gem "pg", "~> 1.1"

# Servidor web
gem "puma", ">= 5.0"

# Assets y JavaScript
gem "sprockets-rails"
gem "jsbundling-rails"
gem "cssbundling-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "bootsnap", require: false

# Windows/JRuby timezone data
gem "tzinfo-data", platforms: %i[ windows jruby ]

# Autenticación
gem "devise", "~> 4.9"

# Autorización
gem "cancancan", "~> 3.5"

# Google Calendar API
gem "google-apis-calendar_v3"

# Envío de emails
gem "sendgrid-ruby"

# Variables de entorno
gem "dotenv-rails"

# Paginación
gem "pagy", "~> 6.0"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
  gem "rspec-rails", "~> 6.0"
  gem "factory_bot_rails"
  gem "faker"
end

group :development do
  gem "web-console"
end